### ISSUE TITLE
轮播图所在fragment中，当轮播图不可见的时候退出app会出现异常

### ISSUE THREAD

**Issue by Rob8it** [uncleleonfan/FunBanner#3]
打开app后，轮播图所在fragment中，当轮播图不可见的时候退出app会出现异常，请处理

具体异常如下：
        java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
                                                                           at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
                                                                           at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
                                                                           at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:87)
                                                                           at com.bumptech.glide.Glide.with(Glide.java:629)
                                                                           at com.leon.loopviewpagerlib.FunBanner$1.instantiateItem(FunBanner.java:188)
                                                                           at com.leon.loopviewpagerlib.LoopPagerAdapterWrapper.instantiateItem(LoopPagerAdapterWrapper.java:86)
                                                                           at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1034)
                                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:1248)
                                                                           at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:668)
                                                                           at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
                                                                           at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:622)
                                                                           at com.leon.loopviewpagerlib.LoopViewPager.setCurrentItem(LoopViewPager.java:95)
                                                                           at com.leon.loopviewpagerlib.LoopViewPager.setCurrentItem(LoopViewPager.java:101)
                                                                           at com.leon.loopviewpagerlib.LoopViewPager$2.run(LoopViewPager.java:234)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by uncleleonfan** [comment]
在1.2.0版本已解决
